<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="200838" started-at="2020-05-14T19:07:29 BST" finished-at="2020-05-14T19:10:50 BST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="200838" started-at="2020-05-14T19:07:29 BST" finished-at="2020-05-14T19:10:50 BST">
      <class name="com.bridgelabz.test.RegistrationTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.bridgelabz.test.RegistrationTest@4d41cee]" name="beforeMethod" is-config="true" duration-ms="32241" started-at="2020-05-14T19:07:37 BST" finished-at="2020-05-14T19:08:09 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="registrationPage(java.lang.String, java.lang.String, java.lang.String, long)[pri:0, instance:com.bridgelabz.test.RegistrationTest@4d41cee]" name="registrationPage" duration-ms="74518" started-at="2020-05-14T19:08:09 BST" data-provider="registerdata" finished-at="2020-05-14T19:09:23 BST">
          <params>
            <param index="0">
              <value>
                <![CDATA[raj]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nayangkumar@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[nayan1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9048200622]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:4200/login] but found [http://localhost:4200/registration]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:4200/login] but found [http://localhost:4200/registration]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.bridgelabz.test.RegistrationTest.registrationPage(RegistrationTest.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registrationPage -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.bridgelabz.test.RegistrationTest@4d41cee]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2020-05-14T19:09:24 BST" finished-at="2020-05-14T19:09:24 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="registrationPage(java.lang.String, java.lang.String, java.lang.String, long)[pri:0, instance:com.bridgelabz.test.RegistrationTest@4d41cee]" name="registrationPage" duration-ms="73547" started-at="2020-05-14T19:09:24 BST" data-provider="registerdata" finished-at="2020-05-14T19:10:37 BST">
          <params>
            <param index="0">
              <value>
                <![CDATA[raj]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nayang]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[nayan1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9048200622]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:4200/login] but found [http://localhost:4200/registration]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:4200/login] but found [http://localhost:4200/registration]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.bridgelabz.test.RegistrationTest.registrationPage(RegistrationTest.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registrationPage -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.bridgelabz.test.RegistrationTest@4d41cee]" name="afterMethod" is-config="true" duration-ms="11892" started-at="2020-05-14T19:10:38 BST" finished-at="2020-05-14T19:10:49 BST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.bridgelabz.test.RegistrationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
